### ISSUE TITLE
Code Quality - Improve Code quality of all segments

### ISSUE THREAD

**Issue by blackonyyx** [AY2021S1-CS2103T-F13-1/tp#153]
At least some evidence of these (see here for more info)
- logging
- exceptions
- assertions
- defensive coding

No coding standard violations e.g. all boolean variables/methods sounds like booleans. Checkstyle can prevent only some coding standard violations; others need to be checked manually.

SLAP is applied at a reasonable level. Long methods or deeply-nested code are symptoms of low-SLAP.

No noticeable code duplications i.e. if there multiple blocks of code that vary only in minor ways, try to extract out similarities into one place, especially in test code.

Evidence of applying code quality guidelines covered in the module.

**Comment by aqcd** [comment]
No more functional code for v1.4.
