### ISSUE TITLE
Bug Report: Display of GUI has Bugs from recipes

### ISSUE THREAD

**Issue by blackonyyx** [AY2021S1-CS2103T-F13-1/tp#51]
addr allows adding a recursive recipe:
That is, a recipe taking in the product as an ingredient in it's recipe.
eg 
fatty + banana -> fatty
eg: 
addi -n fatty -q 100 -d eats bananas -l Bob's banana farm
deli -n banana
addr -n fatty -items fatty[1], banana[1] -pc 1 -d fatty eats bananas

This completely breaks the display of GUI for all recipes
listr does not display anything

Solution Proposed:
Disallow command to add such recipes by adding checks

Edit:
condition is that banana was soft deleted already

**Comment by khenghun** [comment]
Bug fixed
