### ISSUE TITLE
update UG/DG based on comments from cs2101

### ISSUE THREAD

**Issue by aqcd** [AY2021S1-CS2103T-F13-1/tp#86]
Actable comments:

UG
Prof:
- Bold `Inventoryinator` in leading line cos its the name, larger font as well?
- Diagram to top right corner instead
- longer intro, more descriptions that apply uniquely to this app
- smaller diagram for quickstart, taking up too much space
- better use of whitespace
- sample commands not consistent in plurality
- add more to the preface under the features heading
- modify formatting of examples so it doesn't appear to be 2 examples
- made `Recipe` definition clear
- listi and listr need more description (by extension, all examples should be story-like: goal, how to do, result)
- in general, descriptions for features too short, need to explain what it does for the user and not just what it does
- listr `listing all items` -> `recipes`
- personalise intro, don't bother with CLI GUI copypasta
- ** add authorship for grading purposes **

Peer:
- Format legend: Use format heading, include another column to describe format. Add a row for "term ..." explicitly
- Under ‘DESCRIPTION’, shouldn’t the description be for the command/variable term? So, using addi as example, shouldn’t the description be for qty rather than q, desc rather than d etc…? (you even used item name rather than n in the description)
- Features: more examples, esp for commands with optionals
- Formatting of headings can be improved. The space between command and “:” in headings should be kept consistent for all the features. Eg. Adding a new Recipe: addr  vsListing all items : listi
- listi/listr format to be changed
- glossary
- change picture of help url
- formatting of the features section
- delr `bananas` -> `banana`
- remove WIPs

DG:
- more language use of `you`
- identify and introduce the target audience
- table and heading formatting
- review and updates prefaces

Both:
- intro: overview of software
- Use of some technical jargons that are not explained like “argument parameter” in legend

**Comment by Rahul0506** [comment]
Also need to add following commands:
- clear item/recipe
- craft
- edit
- undo/redo

**Comment by aqcd** [comment]
UG section done, DG section remains
